#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	ffmpeg="ffmpeg -hide_banner" \
    gap="git add --patch" \
    gc="git commit" \
    gs="git status" \

alias \
	ls="ls -a -hN --color=auto --group-directories-first" \
    ll="ls -l" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    vw="nvim -c 'VimwikiIndex'" \
    shutdown="sudo shutdown -h now"

mkcd() { mkdir -p "$@" && cd "$@"; }
