#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	ffmpeg="ffmpeg -hide_banner" \
    gap="git add --patch" \
    gc="git commit" \
    gs="git status" \

alias \
	ls="ls -A -hN --color=auto" \
    ll="ls -lt" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    vw="nvim -c 'VimwikiIndex'" \
    shutdown="sudo shutdown -h now"

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

mkcd() { mkdir -p "$@" && cd "$@"; }
