#!/bin/sh
git config --global user.name $GIT_USERNAME
git config --global user.email $GIT_EMAIL
git config --global user.signingkey $GIT_SIGNINGKEY
git config --global commit.gpgsign true

gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

