#!/bin/sh

# XDG
if test -z "${XDG_RUNTIME_DIR}"; then
     export XDG_RUNTIME_DIR="/tmp/${UID}-runtime-dir"
     if ! test -d "${XDG_RUNTIME_DIR}"; then
         mkdir "${XDG_RUNTIME_DIR}"
         chmod 0700 "${XDG_RUNTIME_DIR}"
     fi
fi
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway

# OTHER SOURCES
source "$XDG_CONFIG_HOME/sh/profile-private"

# COMMANDS
$XDG_CONFIG_HOME/sh/commands > /dev/null 2>&1

# PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/share/yabridge"

export EDITOR="vim"
export TERM="foot"
export BROWSER="firefox-wayland"
export LAUNCHER="foot --window-size-pixels=400x200 -a=menu menu"
export TZ='America/Los_Angeles'

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export HISTFILE="$XDG_DATA_HOME/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export SQLITE_HISTORY="$XDG_CACHE_HOME/sqlite_history"                     
export GOPATH="$XDG_DATA_HOME/go"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export CLASSPATH="$XDG_DATA_HOME/java"

# CONFIGS
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export LS_COLORS=$LS_COLORS:'ow=30;44:'
export GPG_TTY=$(tty)

# ENV VAR FOR PLATFORM
if [ -d "/proc/acpi/button/lid" ]; then
    export IS_DESKTOP=0
else
    export IS_DESKTOP=1
fi
